name: run_ptank
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout 
      - uses: actions/checkout@v3
      # Runs a set of commands using the runners shell
      - name: Ptank
        run: |
          wget http://data.phishtank.com/data/5836c016df5f11fc0036f31018da1cb77327a0b0da767badb88cf6ddd488c6e3/online-valid.csv.gz
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Update online-valid.csv.tgz"
          git push
